### ISSUE TITLE
Modificar forma de construir el `title` de las distribuciones

### ISSUE THREAD

**Issue by abenassi** [datosgobar/geoandino-theme#36]
Hoy GeoAndino utiliza el formato de la capa como nombre completo (`title`) de una `distribution`, quedando como nombres:

Azulejos
Vista en Google Earth
KML
PNG
PDF
JPEG
GeoJSON
Excel
CSV
GML 3.1.1
GML 2.0
Archivo zip

Bajo la forma en que figurarían los títulos de las distribuciones en datos.gob.ar o en un Andino, esto sería bastante confuso. Lo que se plantea hacer es construir el `title` de la `distribution` a partir de una concatenación con el `title` del `dataset`:

Template: `distribution_title` = `dataset_title` (`nombre actual de la distribution`)

actividades_humanas (Azulejos)
actividades_humanas (Vista en Google Earth)
actividades_humanas (KML)
actividades_humanas (PNG)
actividades_humanas (PDF)
actividades_humanas (JPEG)
actividades_humanas (GeoJSON)
actividades_humanas (Excel)
actividades_humanas (CSV)
actividades_humanas (GML 3.1.1)
actividades_humanas (GML 2.0)
actividades_humanas (Archivo zip)

**Comment by poligarcia** [comment]
@abenassi esto sólo sería a los efectos e la generación del `data.json`, no? En el modelo de Geoandino queda igual...

**Comment by abenassi** [comment]
Si sí, solo a los efectos de la generación del data.json.

**Comment by lalo73** [comment]
En la implementacion, paso de:
```
{
accessURL: "http://localhost/layers/geonode:actividades_humanas",
downloadURL: "http://localhost/geoserver/geonode/wfs",
issued: "2017-09-26T08:18:01.645575",
title: "OGC WFS: geonode Service"
},
```
a
```
{
accessURL: "http://localhost/layers/geonode:actividades_humanas",
downloadURL: "http://localhost/geoserver/geonode/wfs",
issued: "2017-09-26T08:18:01.645575",
title: "actividades_humanas (OGC WFS: geonode Service)"
},
```

Sería lo esperado, @abenassi ?

**Comment by abenassi** [comment]
Exacto
